name: Deploy static site to haunteddreams.fun
on:
  push: { branches: [ main ] }
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    steps:
      - uses: actions/checkout@v4

      - name: Write SSH key
        shell: bash
        run: |
          umask 077
          printf '%s' "${{ secrets.SSH_KEY }}" | tr -d '\r' > key
          echo "Runner key fingerprint:"
          ssh-keygen -lf key

      - name: Trust server host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Debug SSH (-vvv)
        continue-on-error: true
        run: |
          ssh -vvv -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes -i key \
            "$SSH_USER@$SSH_HOST" 'echo connected && whoami && id'

      - name: Ensure remote dir exists
        run: |
          ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes -i key \
            "$SSH_USER@$SSH_HOST" "install -d -m 755 '$DEPLOY_PATH'"

      - name: Deploy via rsync
        env:
          RSYNC_RSH: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes -i key
        run: |
          rsync -avz --delete \
            --exclude '.git' --exclude '.github' \
            -e "$RSYNC_RSH" ./ "$SSH_USER@$SSH_HOST:$DEPLOY_PATH/"
