name: Deploy static site to haunteddreams.fun
on:
  push: { branches: [ main ] }
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    steps:
      - uses: actions/checkout@v4

      - name: Write SSH key
        run: |
          umask 077
          printf '%s' "${{ secrets.SSH_KEY }}" > key

      - name: Trust server host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Ensure remote dir exists
        run: |
          ssh -i key -o StrictHostKeyChecking=yes "$SSH_USER@$SSH_HOST" \
            "install -d -m 755 '$DEPLOY_PATH'"

      - name: (Optional) Generate WebP if PNGs present
        run: |
          sudo apt-get update -y
          sudo apt-get install -y webp
          cd assets || exit 0
          [ -f hero.png ]   && cwebp -q 82 -resize 1600 0 hero.png   -o hero.webp || true
          [ -f banner.png ] && cwebp -q 82 -resize 1600 0 banner.png -o banner.webp || true

      - name: Deploy via rsync
        env:
          RSYNC_RSH: ssh -i key -o StrictHostKeyChecking=yes
        run: |
          rsync -avz --delete \
            --exclude '.git' --exclude '.github' \
            -e "$RSYNC_RSH" ./ "$SSH_USER@$SSH_HOST:$DEPLOY_PATH/"
