name: Deploy static site to haunteddreams.fun
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > key
          chmod 600 key

      - name: Sync files to server (rsync over SSH)
        run: |
          rsync -avz --delete \
            --exclude '.git' --exclude '.github' \
            -e "ssh -i key -o StrictHostKeyChecking=accept-new" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}/

      - name: Post-deploy: ensure WebP + perms
        run: |
          ssh -i key -o StrictHostKeyChecking=accept-new ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'SSH'
          set -e
          command -v cwebp >/dev/null 2>&1 || (apt-get update && apt-get install -y webp)
          cd ${DEPLOY_PATH:-/var/www/haunteddreams.fun}/assets
          [ -f hero.png ]   && cwebp -q 82 -resize 1600 0 hero.png   -o hero.webp || true
          [ -f banner.png ] && cwebp -q 82 -resize 1600 0 banner.png -o banner.webp || true
          chown -R www-data:www-data ${DEPLOY_PATH:-/var/www/haunteddreams.fun} || true
          SSH
    env:
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
