name: Deploy static site to haunteddreams.fun
on:
  push: { branches: [ main ] }
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    steps:
      - uses: actions/checkout@v4

      - name: Write SSH key (exact bytes, no CRLF) and validate
        shell: bash
        run: |
          umask 077
          printf '%s' "${{ secrets.SSH_KEY }}" | tr -d '\r' > key
          # derive pubkey from private key (this is how to validate a PRIVATE key)
          ssh-keygen -y -f key > key.pub
          echo "Key fingerprint:"
          ssh-keygen -lf key.pub

      - name: Trust server host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Debug SSH connectivity (-vv)
        run: |
          ssh -vv -i key -o IdentitiesOnly=yes "$SSH_USER@$SSH_HOST" \
            'echo "AUTH OK on $(hostname) as $(id -un)"; id; uname -a'

      - name: Ensure remote dir exists
        run: |
          ssh -i key -o IdentitiesOnly=yes "$SSH_USER@$SSH_HOST" \
            "install -d -m 755 '$DEPLOY_PATH'"

      - name: Deploy via rsync
        run: |
          rsync -avz --delete \
            --exclude '.git' --exclude '.github' \
            -e "ssh -i key -o IdentitiesOnly=yes" \
            ./ "$SSH_USER@$SSH_HOST:$DEPLOY_PATH/"
